import { type Product } from "../types";

const GFORM_URL = "https://forms.gle/UD9PxZszKRNfnG1H6";

export const products: Product[] = [
    {
    id: "1",
    slug: "paket-1-dotzy",
    name: "Paket 1 Dotzy",
    category: "bundle",
    price: 90000,
    description: "Bundle lengkap semua produk Dotzy dalam satu paket.",
    longDescription:
      "Paket paling lengkap dari Dotzy! Berisi Stiker Pack, Pin Set, Gantungan Kunci, dan Totebag Canvas sekaligus. Satu paket buat kamu yang mau punya semua koleksi Dotzy dengan harga yang jauh lebih hemat dari beli satuan.",
    specs: [
      "Isi: Stiker Pack + Pin Set + Gantungan Kunci + Totebag Canvas Dotzy",
      "Stiker: Vinyl premium waterproof, 5–8 cm per stiker",
      "Pin: Metal + kaca glossy, diameter 44mm",
      "Gantungan Kunci: Acrylic 3mm double-side, ±5x5 cm",
      "Totebag: Canvas 12oz, 38x42 cm",
    ],
    color: "#FFD93D",
    accentColor: "#f14a1d",
    gformUrl: GFORM_URL,
    images: [
      "/images/product/paket 1.png",
      "/images/product/stiker.png",
      "/images/product/pin.png",
      "/images/product/ganci.png",
      "/images/product/totebag.png",
    ],
  },
  {
    id: "2",
    slug: "paket-2-dotzy",
    name: "Paket 2 Dotzy",
    category: "bundle",
    price: 60000,
    description: "Bundle hemat Totebag Canvas + Stiker Pack Dotzy.",
    longDescription:
      "Paket bundle berisi Totebag Canvas Dotzy dan Stiker Pack Dotzy. Tempel stiker-stiker cute di totebag kamu dan jadikan aksesori sehari-hari yang makin personal. Paket yang pas buat tampil beda ke kampus!",
    specs: [
      "Isi: Totebag Canvas Dotzy + Stiker Pack Dotzy",
      "Totebag: Canvas 12oz, 38x42 cm",
      "Stiker: Vinyl premium waterproof, 5–8 cm per stiker",
      "Desain karakter Dotzy original",
    ],
    color: "#4D96FF",
    accentColor: "#f14a1d",
    gformUrl: GFORM_URL,
    images: [
      "/images/product/paket 2.png",
      "/images/product/totebag.png",
      "/images/product/stiker.png",
    ],
  },
  {
    id: "3",
    slug: "paket-3-dotzy",
    name: "Paket 3 Dotzy",
    category: "bundle",
    price: 40000,
    description: "Bundle hemat Stiker Pack + Pin Set + Gantungan Kunci Dotzy.",
    longDescription:
      "Paket bundle lengkap berisi Stiker Pack, Pin Set, dan Gantungan Kunci Dotzy. Tiga item sekaligus buat kamu yang mau koleksi semua karakter Dotzy favoritmu. Harga spesial, kualitas tetap oke!",
    specs: [
      "Isi: Stiker Pack + Pin Set + Gantungan Kunci Dotzy",
      "Stiker: Vinyl premium waterproof, 5–8 cm per stiker",
      "Pin: Metal + kaca glossy, diameter 44mm",
      "Gantungan Kunci: Acrylic 3mm double-side, ±5x5 cm",
    ],
    color: "#6BCB77",
    accentColor: "#2f318b",
    gformUrl: GFORM_URL,
    images: [
      "/images/product/paket 3.png",
      "/images/product/stiker.png",
      "/images/product/pin.png",
      "/images/product/ganci.png",
    ],
  },
  {
    id: "4",
    slug: "paket-4-dotzy",
    name: "Paket 4 Dotzy",
    category: "bundle",
    price: 30000,
    description: "Bundle hemat Pin Set + Gantungan Kunci Dotzy.",
    longDescription:
      "Paket bundle hemat berisi Pin Set Dotzy dan Gantungan Kunci Dotzy — dua item favorit dalam satu paket. Cocok buat kamu yang mau tampil cute tanpa harus beli satuan. Lebih hemat, lebih seru!",
    specs: [
      "Isi: Pin Set Dotzy + Gantungan Kunci Dotzy",
      "Pin: Metal + kaca glossy, diameter 44mm",
      "Gantungan Kunci: Acrylic 3mm double-side, ±5x5 cm",
      "Desain karakter Dotzy original",
    ],
    color: "#f14a1d",
    accentColor: "#2f318b",
    gformUrl: GFORM_URL,
    images: [
      "/images/product/paket 4.png",
      "/images/product/pin.png",
      "/images/product/ganci.png",
    ],
  },
  {
    id: "5",
    slug: "totebag-canvas-dotzy",
    name: "Totebag Canvas Dotzy",
    category: "totebag",
    price: 50000,
    description: "Totebag canvas tebal dengan desain eksklusif karakter Dotzy.",
    longDescription:
      "Totebag canvas premium 12oz dengan sablon desain eksklusif karakter Dotzy. Kuat menampung buku, laptop tipis, atau belanjaan harian. Tali panjang yang nyaman di bahu. Cocok untuk kuliah, hangout, atau kegiatan sehari-hari.",
    specs: [
      "Bahan: Canvas 12oz",
      "Ukuran: 38x42 cm",
      "Tali panjang: 65 cm",
      "Sablon: Water-based eco ink",
    ],
    color: "#4D96FF",
    accentColor: "#f14a1d",
    gformUrl: GFORM_URL,
    images: [
      "/images/product/totebag.png",
    ],
  },
  {
    id: "6",
    slug: "gantungan-kunci-dotzy",
    name: "Gantungan Kunci Dotzy",
    category: "gantungan-kunci",
    price: 15000,
    description: "Gantungan kunci acrylic karakter Dot & Zy yang lucu.",
    longDescription:
      "Gantungan kunci acrylic dua sisi dengan desain eksklusif karakter Dotzy. Tersedia pilihan karakter Dot (cloud bear) dan Zy (cloud bunny). Material acrylic tebal 3mm, transparan dan jernih. Dilengkapi ring logam anti karat.",
    specs: [
      "Bahan: Acrylic 3mm double-side",
      "Ukuran: ±5x5 cm",
      "Ring logam anti karat",
      "Full colour printing",
      "Tersedia varian: Dot & Zy",
    ],
    color: "#6BCB77",
    accentColor: "#2f318b",
    gformUrl: GFORM_URL,
    images: [
      "/images/product/ganci.png",
      "/images/product/ganci dot.png",
      "/images/product/ganci zy.png",
    ],
    variants: [
      { label: "Ganci Dot", image: "/images/product/ganci dot.png" },
      { label: "Ganci Zy", image: "/images/product/ganci zy.png" },
    ],
  },
  {
    id: "7",
    slug: "pin-set-dotzy",
    name: "Pin Set Dotzy",
    category: "pin",
    price: 15000,
    description: "Set pin button karakter Dotzy, cocok untuk jaket & tas.",
    longDescription:
      "Set pin button dengan desain cute & playful karakter Dotzy. Terbuat dari metal dengan kaca depan glossy. Ukuran standar 44mm pas banget ditempel di jaket jeans, tas, atau topi kamu. Hadir dalam set lengkap karakter Dot dan Zy.",
    specs: [
      "Bahan: Metal + kaca glossy",
      "Diameter: 44mm",
      "Desain karakter Dotzy original",
      "Jarum pengunci aman",
    ],
    color: "#f14a1d",
    accentColor: "#2f318b",
    gformUrl: GFORM_URL,
    images: [
      "/images/product/pin.png",
    ],
  },
  {
    id: "8",
    slug: "stiker-pack-dotzy",
    name: "Stiker Pack Dotzy",
    category: "stiker",
    price: 10000,
    description: "Pack stiker vinyl waterproof motif karakter Dotzy yang cute.",
    longDescription:
      "Dapatkan pack stiker vinyl premium bergambar karakter Dotzy — Dot dan Zy! Tahan air dan sinar UV, cocok untuk laptop, tumbler, notebook, atau mana saja yang kamu mau. Dicetak dengan tinta berkualitas tinggi agar warna tetap cerah.",
    specs: [
      "Bahan: Vinyl premium waterproof",
      "Ukuran: 5–8 cm per stiker",
      "Tahan air & UV",
      "Desain karakter Dotzy original",
      "Tersedia varian: Dot & Zy",
    ],
    color: "#FFD93D",
    accentColor: "#f14a1d",
    gformUrl: GFORM_URL,
    images: [
      "/images/product/stiker.png",
      "/images/product/stiker dot.png",
      "/images/product/stiker zy.png",
    ],
    variants: [
      { label: "Stiker Dot", image: "/images/product/stiker dot.png" },
      { label: "Stiker Zy", image: "/images/product/stiker zy.png" },
    ],
  },
];